### ISSUE TITLE
[Mod] B1 Centauro 120  半人马 120炮 

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#1]
![in-game](https://user-images.githubusercontent.com/12712112/53006900-26e4fa00-3471-11e9-9795-2d8b38a68043.png)

**Description:**

The Centauro is a family of Italian military vehicles originating from a wheeled tank destroyer for light to medium territorial defense and tactical reconnaissance. It was developed by a consortium of manufacturers, the Società Consortile Iveco Fiat - Oto Melara (CIO). Iveco Fiat was tasked with developing the hull and propulsion systems while Oto Melara was responsible for developing the turrets and weapon systems.

Over the years, the Centauro platform has been developed into multiple variants to fulfill other combat roles, such as infantry fighting vehicle or self-propelled howitzer.

**Download Link:** 

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-B1-Centauro-120.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-B1-Centauro-120.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by theblackheartfox** [comment]
Can you plz app thr wt auf panzer 4 in late world war 2
