### ISSUE TITLE
[Mod] Hummel

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#12]
Hummel (German: "bumblebee") was a self-propelled gun based on the Geschützwagen III/IV chassis and armed with a 15 cm howitzer. It was used by the German Wehrmacht during the Second World War from early 1943 until the end of the war.

The full name was Panzerfeldhaubitze 18M auf Geschützwagen III/IV (Sf) Hummel, Sd.Kfz. 165. On February 27, 1944, Hitler ordered the name Hummel to be dropped as it was deemed inappropriate for a fighting vehicle.

![Hummel](https://user-images.githubusercontent.com/12712112/57123378-255e7900-6db4-11e9-9668-c30e24468db6.jpg)

**Download Links:**

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-Hummel.modpack?raw=true)
[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-Hummel.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Doreamonsky** [comment]
![1](https://user-images.githubusercontent.com/12712112/57123480-8d14c400-6db4-11e9-8ba3-d3a9317e4765.png)
![5](https://user-images.githubusercontent.com/12712112/57123484-8e45f100-6db4-11e9-9bfa-a83c4687814b.png)

**Comment by KuzyaG** [comment]
Add please Skorpion G

**Comment by theblackheartfox** [comment]
I have notice the make has a problem every time you aim at the ground the barrel poinys strat and up to the front plz fix
