### ISSUE TITLE
[Mod] RhB Waffentrager

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#13]
![951c22d7c1b2991e44dbbef0ec8f525a2638922a](https://user-images.githubusercontent.com/12712112/57188386-5bc10300-6f30-11e9-891c-9e08a0e4c891.png)

Download Links:

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-RhB_Waffentrager.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-RhB_Waffentrager.modpack?raw=true)

Change Logs:
2019/05/11
Alpha Damage Buff to 750

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by theblackheartfox** [comment]
Omg!!!!! Thxs

**Comment by theblackheartfox** [comment]
Add is- 7 to late ww2

**Comment by Childrek** [comment]
Please Object-705A
Cold war:)
