### ISSUE TITLE
[Mod] Sherman Jumbo

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#14]
![4f7edb064718fefd2dbf6ea86542b81838948b44](https://user-images.githubusercontent.com/12712112/57188380-3c29da80-6f30-11e9-94c7-6fddcd88d7d3.png)

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-Sherman_Jumbo.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-Sherman_Jumbo.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by KuzyaG** [comment]
Add Skorpion G please!!

**Comment by theblackheartfox** [comment]
Please look I to your auto aim mech it won't lock on for me
