### ISSUE TITLE
Kv-4

### ISSUE THREAD

**Issue by theblackheartfox** [Doreamonsky/Panzer-War-Lit-Mod#15]
The texture on tge tracks for this game are whit pleas look into it

**Comment by StrelokTvHd** [comment]
Please add 2 types of KV-4 to the game))
KV-4 Kreslavskiy - https://sketchfab.com/3d-models/kv-4-kreslavskiy-5b70632ac37841ffb9c8daa1734b734d
KV-4 - https://sketchfab.com/3d-models/kv-4-a5d2d75a5bda4f9cbaabc953d2802d6d
