### ISSUE TITLE
[Mod] FV 4005 !

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#18]
![FV4005](https://user-images.githubusercontent.com/12712112/57972298-eee74780-79ca-11e9-8567-45ef25b9967e.jpg)

 This tank destroyer project was developed on the basis of the Centurion Mk3 tank in the early 1950s.

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-FV4005.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-FV4005.modpack?raw=true)

Change Log:
2019/05/25 
The max turret turning angle changed to 110 degress.
Fix HESH shell bugs.

**Do not leave comments like adding tanks!!!**

If you like ,make it yourself ,or play [World of Tanks](https://worldoftanks.com/)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by CahyoKusum** [comment]
Finnaly!!!!

**Comment by CahyoKusum** [comment]
Now add AMX 50 b

**Comment by CahyoKusum** [comment]
I want new aiming circle

**Comment by KuzyaG** [comment]
Wow!

**Comment by theblackheartfox** [comment]
Yeah we do need a new aiming circle

**Comment by Drylov80** [comment]
Добавьте колёсников пожалуйста

**Comment by WoTIdeas** [comment]
Add the Jg. Pz E100 please thank you very much.
