### ISSUE TITLE
Why do we use mod to add new tanks?

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#19]
First of all, mods are flexible for updates. You don't need to wait for a complete release of the new version.

Secondarily,you can decide what tanks should be in the game. (Someone do not like tanks such as FV 4005)

Thirdly, it can reduce the apk size!

**Do not leave comments like adding tanks!!!**

If you like ,make it yourself ,or play [World of Tanks](https://worldoftanks.com/)

**Comment by CahyoKusum** [comment]
Can you add AMX 50 b Grille 15 Jagdpanzer E100 Tiger(P) Skorpion G

**Comment by NEXT29297** [comment]
Same with CahyoKusum and t95 :)
I can wait for that. You game is good :)

**Comment by Doreamonsky** [comment]
**Do not leave comments like adding tanks!!!**

If you like ,make it yourself ,or play [World of Tanks](https://worldoftanks.com/)

**Comment by Childrek** [comment]
Object 705A

**Comment by NEXT29297** [comment]
Ok sorry :{

**Comment by WangRui123qwe** [comment]
like it🙄🙃🙃🙃😊

**Comment by CahyoKusum** [comment]
Sorry

**Comment by Gamesrfry** [comment]
Hey there are rendering engine option in the settings right there are four types so what are the differences between those four rendering engine?

**Comment by Viper2463** [comment]
Add Jagdpanzer E100 pllis

**Comment by Olt13** [comment]
Т-14 and T-14-152 for Cold War, please.
BT-42 for middle WWII.
Т-44 for late WWI.

**Comment by margarcz** [comment]
Ferdinand,lt38,lt35
