### ISSUE TITLE
[Mod] T-72 Soviet MBT 苏联主战坦克

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#2]
![t-72](https://user-images.githubusercontent.com/12712112/53088080-ae9b3900-3543-11e9-9e3e-d0b432184af2.png)

**Description** 
The T-72 is a family of Soviet main battle tanks that first entered production in 1971. About 20,000 T-72 tanks were built, making it one of the most widely produced post-World War II tanks, second only to the T-54/55 family. The T-72A version introduced in 1979 is considered a second-generation main battle tank. It was widely exported and saw service in 40 countries and in numerous conflicts. The T-72B3 version introduced in 2010 is considered a third-generation main battle tank.

**Download Link** 
[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-T-72.modpack?raw=true)
[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-T-72.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Maharlika-Mapping** [comment]
Hello, I've noticed that the Android version has a bug. The Texture is broken for the model. All I could see is bright pink. Only the tracks are colored

**Comment by Doreamonsky** [comment]
@Maharlika-Mapping I will check it.

**Comment by CahyoKusum** [comment]
Can you add AMX 50 B Mod plss?
