### ISSUE TITLE
[Mod] Type 2605

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#23]
The Type 5, also known as the Type 2605, was one of the variants of the O-I superheavy tank, developed during WWII. The vehicle was planned to be used for breaking through fortified enemy lines and for coastal defense.

Android: https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-Type_2605.modpack?raw=true
Windows: https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-Type_2605.modpack?raw=true

ChangeLog:
Change Gun from 140 mm to 150 mm with new HE shell.

![Type_2605](https://user-images.githubusercontent.com/12712112/61180161-a784dc80-a644-11e9-8e52-e267ff621e11.jpg)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Childrek** [comment]
Oh,my...You crazy mean!!)))
