### ISSUE TITLE
[Mod] Centurion AX

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#27]
![timg](https://user-images.githubusercontent.com/12712112/61871295-100c6d00-af13-11e9-9b71-bb6e48f25d2e.jpg)

Android: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-Centurion_Action_X.modpack?raw=true>

Windows : <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-Centurion_Action_X.modpack?raw=true>

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by NEXT29297** [comment]
What a big update!!, I can play all summer too!! lol

**Comment by Olt13** [comment]
Awaiting T-14-152

**Comment by CahyoKusum** [comment]
I still wait for AMX 50
