### ISSUE TITLE
ダージリン /Darjeeling/大吉岭 Vocie Pack 

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#29]
Android: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_%E3%83%80%E3%83%BC%E3%82%B8%E3%83%AA%E3%83%B3.modpack?raw=true>

Windows: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_%E3%83%80%E3%83%BC%E3%82%B8%E3%83%AA%E3%83%B3.modpack?raw=true>

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by NEXT29297** [comment]
Thank for this girl, i have been wait for long time =3=
