### ISSUE TITLE
Kuro Mori Mine Voice Pack

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#30]
Android: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_KuroMoriMine.modpack?raw=true>

Windows: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_KuroMoriMine.modpack?raw=true>

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by LilSpongeBob** [comment]
Bring back the National crew voice
