### ISSUE TITLE
[Mod] TVP 50/51

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#36]
![T50_51](https://user-images.githubusercontent.com/12712112/63022561-c55c9000-bed5-11e9-9450-f6dd4a8b1249.jpg)

Download Link: 

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-T50_51.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-T50_51.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by theblackheartfox** [comment]
I cant download

**Comment by Doreamonsky** [comment]
> I cant download

Fixed

**Comment by theblackheartfox** [comment]
Thanks

**Comment by verver10** [comment]
I cant download
