### ISSUE TITLE
[Mod] Material Fix

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#4]
The addon is made to fix the pink material while you are using the mod vehicle.
此模块用于修复紫色载具

Download Link:

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Material-Fix.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Material-Fix.modpack?raw=true)

**Comment by gersamm** [comment]
У меня фз розовая и т 72 розовый я скачал но не изменилось😞😞😞😞😞😭😭😭😭😭😭😭

**Comment by Doreamonsky** [comment]
@gersamm  It has been fixed.Try it again please!
