### ISSUE TITLE
[Mod] Progetto-65  - Drum Support

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#41]
![Screenshot (1030)](https://user-images.githubusercontent.com/12712112/63209381-9d0da500-c112-11e9-91dd-c876926ef433.png)

**Game Version: 2019.5.2.3 + required** 

Download Link: 

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-Progetto-65.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-Progetto-65.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Jethro131** [comment]
Sir! The tank is not firing on the reload time it say reloaded!!

**Comment by Childrek** [comment]
Fix please .

**Comment by Polkash01** [comment]
Please system DataReady tank of Progetto 65

**Comment by Doreamonsky** [comment]
> Sir! The tank is not firing on the reload time it say reloaded!!

Update game plz

**Comment by Doreamonsky** [comment]
> Fix please .

Update game plz.

**Comment by Doreamonsky** [comment]
> Please system DataReady tank of Progetto 65

Update game plz.

**Comment by giffany** [comment]
"drum"...hm...so now i can play drums in a tank?...cool....

**Comment by AndroidSimulationGames** [comment]
The mod works fine to my game. My apk is updated to the latest version. i think the capacity of the drum is 4 shells if im not mistaken. Thanks for this new mod👍
