### ISSUE TITLE
[Mod]  Strv M42

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#46]
Author - User Renamed : <https://vk.com/renemed_user>

Android <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Sazonov-Roman/Android_Vehicle_StrvM42_modpack.modpack?raw=true>

Windows <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Sazonov-Roman/StandaloneWindows64_Vehicle_StrvM42-1_modpack.modpack?raw=true>

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Polkash01** [comment]
Add please

https://sketchfab.com/3d-models/object-279-early-6e4adc6b74d347e6885a7a3f5c209bab

https://sketchfab.com/3d-models/panhard-ebr-75-fl-10-e38a8ca667034819929aff2870227db4

https://sketchfab.com/3d-models/su-130pm-9bcf04f3b21045aaada26acc58d9ab44

https://sketchfab.com/3d-models/rheinmetall-skorpion-g-f58ac175427b4dffb092e6b929c79d8d

**Comment by shinano-dev** [comment]
Please armataㅠㅠ

https://sketchfab.com/3d-models/armata-152-52e901ef3954431a8d53d3da99c15797

If it's not balanced, create a new modern mode

**Comment by shinano-dev** [comment]
And m1a2 abrams,t90 ms pls

**Comment by shinano-dev** [comment]
M1a2

https://sketchfab.com/3d-models/abrams-3fa4cca419ae4b1c80b8652798dc83e3
