### ISSUE TITLE
[Mod] Nation Voice Pack

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#47]
Android: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_NationalVoicePack.modpack?raw=true>

Windows: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_NationalVoicePack.modpack?raw=true>

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by NEXT29297** [comment]
Very nice :+1:

**Comment by LilSpongeBob** [comment]
Thanks for returning the nationial crew voice

**Comment by LilSpongeBob** [comment]
Since i enjoyed the mod, i suggest you add the module damage just like you did on Cry of War

**Comment by HunGabi22** [comment]
Please make a chinese heavy tank, like WZ111Model5A, or WZ113

**Comment by HunGabi22** [comment]
https://sketchfab.com/3d-models/wz-111-model-5a-c39a46277a4d462ca1e84ea9ad7b96ae
Here is the model for the WZ111 Model 5A
Please make it
