### ISSUE TITLE
[Mod] Ferdinand

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#48]
Author - User Renamed : <https://vk.com/renemed_user>

Android <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Renamed-User/Android_Vehicle_SdKfz184_modpack.modpack?raw=true>

Windows <https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Renamed-User/StandaloneWindows64_Vehicle_SdKfz184_modpack.modpack?raw=true>

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by LilSpongeBob** [comment]
Thank you

**Comment by shinano-dev** [comment]
Please armataㅠㅠ this is 5$
Please 
https://sketchfab.com/3d-models/armata-152-52e901ef3954431a8d53d3da99c15797

If it's not balanced, create a new modern mode
If this famous tank is added, the user flow will be good.

**Comment by LilSpongeBob** [comment]
Add module damage just like you did on Cry of War. I'll wait when the issue releases.

**Comment by NEXT29297** [comment]
LilSpongeBob+1
If have a new mode (realistic mode?) that have to destroy tank like cry of war. It will be a awesome!!

**Comment by LilSpongeBob** [comment]
Ikr

**Comment by Childrek** [comment]
Fix please.
Installed the mod, but Ferdinand did not appear, fluorinated 2 times. The mod with voice acting also did not installs.

**Comment by giffany** [comment]
and the elephant arrives in panzer war.

**Comment by LilSpongeBob** [comment]
And also, why did you nerfed the KV-1 and why did you removed the Panzer 38 (t)?

**Comment by LilSpongeBob** [comment]
And lastly, add new camofludges for all tanks

**Comment by piibr** [comment]
https://sketchfab.com/3d-models/m41-walker-bulldog-1eca62d67e8f4996819c6727f0613d7c

**Comment by piibr** [comment]
https://sketchfab.com/3d-models/e-50-ausf-m-925d7a47c693486e9fe9797f6a21f357

**Comment by LilSpongeBob** [comment]
And lastly, add BT-42 or BT-7 Artillery
