### ISSUE TITLE
[Mod] WT PZ4

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#49]
![lsLkMwRe0-Y](https://user-images.githubusercontent.com/12712112/63950752-29bf4800-caaf-11e9-968d-cfcf6ee1d3ef.jpg)

Made By [Botovich Vzhukh](https://vk.com/bot_botovich_1)

Download Link: 

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Botovich-Vzhukh/Android_Vehicle-WT_pz_4_modpack.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Botovich-Vzhukh/StandaloneWindows64_Vehicle-WT_pz_4_modpack.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Object252U** [comment]
Nice:)

**Comment by LilSpongeBob** [comment]
Now add the module damage
