### ISSUE TITLE
[Mod] SU 152

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#52]
Made By [Botovich Vzhukh](https://vk.com/bot_botovich_1)

Download Link: 

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Botovich-Vzhukh/Android_Vehicle-SU152_modpack.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Botovich-Vzhukh/StandaloneWindows64_Vehicle-SU152_modpack.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by mega330** [comment]
Wow this is great!

**Comment by Jethro131** [comment]
Russian bias!!!!!!

**Comment by Erwinrommel131** [comment]
I have an funny issue there are only the 152mm floating and two track moving

**Comment by piibr** [comment]
More he damage
