### ISSUE TITLE
[Mod] IS-3 D-25t

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#53]
Made By [Botovich Vzhukh](https://vk.com/bot_botovich_1)

Download Link: 

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Botovich-Vzhukh/Android_Vehicle-IS-3_D-25t_modpack.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Third-Part/Botovich-Vzhukh/StandaloneWindows64_Vehicle-IS-3_D-25t_modpack.modpack?raw=true)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Farhan160** [comment]
Pls add some ebr 105 because i cant make that tank

**Comment by Polkash01** [comment]
Farhan160, And mod on sous-130pm or scorpion g can make???

**Comment by Farhan160** [comment]
Sorry i cant polkash 01 because my computer cannot to build some mod

**Comment by Polkash01** [comment]
Farhan160, Got it.

**Comment by LilSpongeBob** [comment]
Thanks for uploading
