### ISSUE TITLE
[Mod] Chinese Tank Pack for National Day

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#55]
Assemble of Type62C WZ111-5A 113 121B WZ111-G-TF

Download Link: 

[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_CN_Pack.zip?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_CN_Pack.zip?raw=true)

Updated: 2019/10/6
IS-2
[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-IS-2.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-IS-2.modpack?raw=true)

====================================

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Doreamonsky** [comment]
国内源：https://dev.tencent.com/u/Doreamonsky/p/Panzer-War-Mod-Storage/git/tree/master

**Comment by Object252U** [comment]
祖国万岁!!!

**Comment by Farhan160** [comment]
Thanks for new mod.i think u can add some tank vk 72.01

**Comment by NEXT29297** [comment]
Me: oww~~ Chinese IS7 
In game. 
Me: What? Just strv M24 can kill me ¬?¬
(REAL THICK ARMOR 030)

**Comment by giffany** [comment]
extra thicc

**Comment by LilSpongeBob** [comment]
@Doreamonsky, for the improvements of the game, optimize and improve the graphics
