### ISSUE TITLE
[Mod] SU-130 PM

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#56]
[Android](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-SU-130PM.modpack?raw=true)

[Windows](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/StandaloneWindows64_Vehicle-SU-130PM.modpack?raw=true)

**Do not leave comments like adding tanks!!!**

If you like ,make it yourself ,or play [World of Tanks](https://worldoftanks.com/)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

**Comment by Polkash01** [comment]
Doreamonsky, Thanks for this mod

**Comment by Farhan160** [comment]
Please add some grille 15

**Comment by Farhan160** [comment]
I am so need grille 15

**Comment by Polkash01** [comment]
Farhan160, Like you wrote that you want to fashion - do it yourself.

**Comment by Farhan160** [comment]
?

**Comment by Polkash01** [comment]
Farhan160, Don't you understand me?

**Comment by NEXT29297** [comment]
@Farhan160, I know that feel, but this game is developed by one person so he can't make a lot a of mod as request. so if want any tank, yeah play wot or war thunder

**Comment by NEXT29297** [comment]
@Polkash01 we have same feel yeah? , we are friends right now :3
Lets help him :]

**Comment by Polkash01** [comment]
NEXT29297,Understand, I'm Russian.

**Comment by Farhan160** [comment]
Ok thanks

**Comment by NEXT29297** [comment]
Haha, i below you :/ i thai

**Comment by NEXT29297** [comment]
How to read Russia? I don't know it :(
What is this ы? And more щ, г, ж, к
Maybe i will learn russia language

**Comment by Polkash01** [comment]
NEXT29297, Give it a shot.

**Comment by Gabriel0182o** [comment]
T49

**Comment by Farhan160** [comment]
Hi i am from indonesia my age is 11
