### ISSUE TITLE
[Mod] Community Mod Pack V1

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#57]
Здравия желаю танкисты ,сегодня выходит MOD PATCH V 1.0😄
Надеемся, вы оцените наши старания и поддержите нас .
Предлагаем вам,отправится в бой на новых машинах , ведь каждая из них уникальна .😄

В БООООООЙ!🔥

![Screenshot_2019-10-14-22-42-06-986_com shanghaiwindy PanzerWarOpenSource](https://user-images.githubusercontent.com/12712112/66800899-a3b96c80-ef49-11e9-989c-d7c1971fbffb.png)

[How to install the mod? Click Here](https://github.com/Doreamonsky/Panzer-War-Lit-Mod)

[如何安装模组? 点击这里](https://github.com/Doreamonsky/Panzer-War-Lit-Mod/wiki/%E6%A8%A1%E7%BB%84%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%8D%97)

E-75_TS
Android: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage-02/blob/master/Botovich/Android_Vehicle-E-75_TS.modpack?raw=true>

Windows: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage-02/blob/master/Botovich/StandaloneWindows64_Vehicle-E-75_TS.modpack?raw=true>

Emil_II
Android: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage-02/blob/master/Botovich/Android_Vehicle-Emil_II.modpack?raw=true>

Windows: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage-02/blob/master/Botovich/StandaloneWindows64_Vehicle-Emil_II.modpack?raw=true>

Object_726
Android: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage-02/blob/master/Botovich/Android_Vehicle-Object_726.modpack?raw=true>

Windows: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage-02/blob/master/Botovich/StandaloneWindows64_Vehicle-Object_726.modpack?raw=true>

T29
Android: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage-02/blob/master/Botovich/Android_Vehicle-T29.modpack?raw=true>

Windows: <https://github.com/Doreamonsky/Panzer-War-Mod-Storage-02/blob/master/Botovich/StandaloneWindows64_Vehicle-T29.modpack?raw=true>

**Comment by Doreamonsky** [comment]
![Screenshot_2019-10-14-22-38-37-355_com shanghaiwindy PanzerWarOpenSource](https://user-images.githubusercontent.com/12712112/66800806-4a513d80-ef49-11e9-8364-dd1028573ecf.png)
![Screenshot_2019-10-14-22-38-49-118_com shanghaiwindy PanzerWarOpenSource](https://user-images.githubusercontent.com/12712112/66800807-4ae9d400-ef49-11e9-82e3-0e6d57976220.png)
![Screenshot_2019-10-14-22-38-58-408_com shanghaiwindy PanzerWarOpenSource](https://user-images.githubusercontent.com/12712112/66800808-4ae9d400-ef49-11e9-9f9f-e70dba9d4604.png)
![Screenshot_2019-10-14-22-39-55-310_com shanghaiwindy PanzerWarOpenSource](https://user-images.githubusercontent.com/12712112/66800810-4b826a80-ef49-11e9-809a-4bb25b949358.png)

**Comment by Cristidanu** [comment]
Wow

**Comment by Farhan160** [comment]
Nice thx for mod

**Comment by Farhan160** [comment]
I like that because u so good

**Comment by CahyoKusum** [comment]
MORE MOOOODDDSS!!

**Comment by daenarvon-dolbaeb** [comment]
add t22 medium and fv4201/chieftain please doreamonsky

**Comment by Gabriel0182o** [comment]
T49 plz

**Comment by denispanzerwar** [comment]
Go AE I PHASE

**Comment by KujouOct** [comment]
After the update of the game today, I find E100, E75, etc. are no where to be found. Are they removed from the game? But why???

**Comment by Doreamonsky** [comment]
You can subscribe them in the workshop.



---Original---

**Comment by LilSpongeBob** [comment]
@Doreamonsky, for the next update, can we upgrade our tanks??

**Comment by Farhan160** [comment]
Hi

**Comment by fury1945** [comment]
Add the late war version of this tank like t-34 heavy tank

**Comment by bekfazt** [comment]
Hi I would be pleased if you will add the BlackPrince British heavy tank. (Churchill series of tanks)  here's the link to the 3D model: https://sketchfab.com/3d-models/black-prince-86b986041e8e47b39194d9ab150d1b95

I'm not sure if you have to buy it to create the tank but if so please reply my comment
