### ISSUE TITLE
[Mod] Legacy-Pack

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#58]
Android:
<https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/Android_Vehicle-Legacy-Pack.modpack?raw=true>

Windows:
<https://steamcommunity.com/sharedfiles/filedetails/?id=1893157554>

This mod is only for Panzer War version 2019.6+.Otherwise,you don't need to download this mod.

**Comment by Doreamonsky** [comment]
These tanks are removed in the newest update for obvious reason. And,you can only play them by adding them as mod.

**Comment by Doreamonsky** [comment]
国内下载分流下载QQ群:225294325 
见群文件

**Comment by Farhan160** [comment]
Thx for the mod,if can add EBR 105 pls

**Comment by Farhan160** [comment]
Thx for mod

**Comment by Farhan160** [comment]
Wait what is it

**Comment by denispanzerwar** [comment]
Not instant mod

**Comment by denispanzerwar** [comment]
No tanks

**Comment by LilSpongeBob** [comment]
Thanks

**Comment by Farhan160** [comment]
Please mod skin legendary for tanks

**Comment by Iffaan24** [comment]
Wher can i find the newest version?

**Comment by bloodbrick** [comment]
Hi
Ive heard about m26 pershing but never found it
Is it only available for paid version?

**Comment by LilSpongeBob** [comment]
@Doreamonsky, are u planning for a new update?

**Comment by piibr** [comment]
> Olá,
> ouvi falar do m26 pershing, mas nunca o encontrei. Ele
> está disponível apenas para a versão paga?

M26 on daily rewards

**Comment by Farhan160** [comment]
Please add tank sheridan

**Comment by shinano-dev** [comment]
If you press enterthegame after the update Exit during loading 
Pls fix bug update....@Doreamonsky
