### ISSUE TITLE
T-34

### ISSUE THREAD

**Issue by busyice** [Doreamonsky/Panzer-War-Lit-Mod#60]
Add T-34 russian tank

**Comment by Mansur338** [comment]
Это мод?

**Comment by Istalin** [comment]
Have t 34 in the game

**Comment by fury1945** [comment]
T-34 heavy tank?

**Comment by Istalin** [comment]
Oh no

Em sex, 20 de dez de 2019 18:44, fury1945 <notifications@github.com>
escreveu:

**Comment by Waw-dev** [comment]
Как скачать?

**Comment by Istalin** [comment]
Kak


Em seg, 30 de dez de 2019 07:16, Waw-dev <notifications@github.com>
escreveu:

**Comment by ivanIRIJ** [comment]
Please add this tanks or a mod:
1.M36 Slugger
2.M18 Hellcat
3.T30 Heavy Tank
4.17pdr SP Achilles
5.M163 VADS
6.M3 Bradley

**Comment by Istalin** [comment]
Have T30

Em sáb, 28 de mar de 2020 11:11, ivanIRIJ <notifications@github.com>
escreveu:
