### ISSUE TITLE
News Updates

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#61]
Follow the post to get the latest news about the mods.

![批注 2020-02-01 190208](https://user-images.githubusercontent.com/12712112/73591100-5cb9ac00-4525-11ea-8693-f9911c0f07b3.jpg)

**Comment by Doreamonsky** [comment]
[PzIV-H Download](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/ReadMe.md#android_vehicle-pziv-h)

![PzIV-H](https://user-images.githubusercontent.com/12712112/73591012-570f9680-4524-11ea-9c39-5b7df3bf1a33.jpg)

Research Tech:

![批注 2020-02-01 185920](https://user-images.githubusercontent.com/12712112/73591092-457abe80-4525-11ea-8f5b-514fa57349ff.jpg)

**Comment by Doreamonsky** [comment]
[ST-II download](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/ReadMe.md#android_vehicle-st-ii)

![PW-ST-II](https://user-images.githubusercontent.com/12712112/73745631-701b8000-478e-11ea-9a74-cd741e5e7e68.png)

**Comment by NEXT29297** [comment]
Thanks for this page
(the download mod page so confuse) :D

**Comment by Doreamonsky** [comment]
[RU 251](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/ReadMe.md#android_vehicle-ru251)

![Ru251](https://user-images.githubusercontent.com/12712112/73928985-fc54b100-490e-11ea-86d7-43f4ddee4abf.jpg)

**Comment by ZoltisToth** [comment]
Please add Grille15 or Jg.Pz.E100 thanks and mods are beautiful

**Comment by LilSpongeBob** [comment]
Quick Poll:
Which tanks or other armored vehichles do you like(choose one by commenting): M50 Ontos(It's a SPG used in the Vietnam War and you can play it on War Thunder)
Or R3 T20 FA-HS(The Italian Self-Propelled Anti Aircraft Gun from War Thunder)
Or ZSU-23-4(Soviet SPAAG)
Or ZSU-57-2(Soviet SPAAG)
Or ASU-57
Or BA-11
Or Wirbelwind(German WW2 SPAAG)
Or Panzerwerfer(German WW2 MLRs)
Or Katyusha(Soviet WW2 MLRs)
Or 2K22 Tunguska(Russian SPAAG)

**Comment by Doreamonsky** [comment]
[Object-907](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/ReadMe.md#android_obj-907)

![PW-Obj907](https://user-images.githubusercontent.com/12712112/74104674-f7536400-4b91-11ea-9e76-d4898aee8990.png)

**Comment by timurchik228** [comment]
Please, belittle either open or add wz111-5a and still could not add more maps similar to wot blitz because the most normal map is the desert ,and I would like such as mines from wot blitz.

**Comment by fury1945** [comment]
Please add m1a2 sep  with 120mm gun and tusk armor

**Comment by Mk48-a1** [comment]
Ill ask this ahain and again till i got my answers. Wheres the missing mod tanks?

For example, t29 and e-75 ts or even obj 279

Were able to download them in the past month but now its gone. I haven't save them so i lost their files and when i came back to download. They are gone. We need answers so please.. Please

**Comment by ZoltisToth** [comment]
Mk48-a1 
T29 Is in modpatch v.1:https://m.vk.com/doc183062388_519581266?hash=7184f358f14c3ddc80&dl=2fdf93f1c636136b1b
E-75 Is in Legacy mod and obj.279 u can't download

**Comment by ZoltisToth** [comment]
Btw i can't find mod E100 H, pls give me link😞

**Comment by Mk48-a1** [comment]
> Mk48-a1
> T29 Is in modpatch v.1:https://m.vk.com/doc183062388_519581266?hash=7184f358f14c3ddc80&dl=2fdf93f1c636136b1b
> E-75 Is in Legacy mod and obj.279 u can't download

Thanks you very much

**Comment by ZoltisToth** [comment]
Mk48-a1 
No problem bro

**Comment by ZoltisToth** [comment]
Mk48-a1 
No problem bro👋🏼

**Comment by ZoltisToth** [comment]
Mk48-a1 
No problem bro👋🏼

**Comment by ZoltisToth** [comment]
I have an idea pls made T28 Defender, IS3 Defender, Mk.1 Defender please,

**Comment by AdrienPurdy** [comment]
Asus57 or m22 locust

**Comment by CahyoKusum** [comment]
AMX 50 b and Foch 155 pls

**Comment by ZoltisToth** [comment]
I NEED HELP I CAN'T FIND MOD WZ-111-5A PLS HELP😰😱😱

**Comment by timurchik228** [comment]
You will not find it because it was deleted or rather blocked by the developer himself

**Comment by NEXT29297** [comment]
> I have an idea pls made T28 Defender, IS3 Defender, Mk.1 Defender please,

Why not all Premium tank in wot 😂

**Comment by ZoltisToth** [comment]
> > I have an idea pls made T28 Defender, IS3 Defender, Mk.1 Defender please,
> 
> Why not all Premium tank in wot

Yess

**Comment by LilSpongeBob** [comment]
Anyways thanks for adding the T49

**Comment by ZoltisToth** [comment]
Why nobody add mods?I want more

**Comment by LilSpongeBob** [comment]
Suggestion: Why not create a tank tech tree ?

**Comment by timurchik228** [comment]
> I have an idea pls made T28 Defender, IS3 Defender, Mk.1 Defender please,

I can throw you an object 252u defender from WOT on the PC

**Comment by timurchik228** [comment]
Hey people i can  throw t22sr ,M6A2E1 ,object 703 ll,object 252u defender ,o-ni,ro go ,gross traktor ,object 260,wz111-5A,121B,object 279,t67 ,Jg.pz.e100 And much more for free, just throw off your whatsapp or VK or here is my nickname in VK-Skril Slech

**Comment by timurchik228** [comment]
> I NEED HELP I CAN'T FIND MOD WZ-111-5A PLS HELP

I can throw WZ111-5A for free ,in VK my nickname Skril Slech

**Comment by timurchik228** [comment]
> Please add Grille15 or Jg.Pz.E100 thanks and mods are beautiful

I can throw you Jg.pz.e100 ,my nickname in VK - Skril Slech

**Comment by MaxiiAlfaro** [comment]
How do you send them by vk?  I just became a user but I don't know how to use it :)

**Comment by timurchik228** [comment]
> How do you send them by vk? I just became a user but I don't know how to use it :)

Заходишь в беседу с человеком и там будет слева скрепка ,нажимаешь на нее и листаешь вправо и там будет ярлык "документы" надимаешь на него и нажимаешь "прочие" ,а там выбераешь то что хотел прикрепить 

You go into a conversation with a person and there will be a paper clip on the left, click on it and scroll to the right and there will be a label "documents" push on it and click "other" ,and there you choose what you wanted to attach

**Comment by MaxiiAlfaro** [comment]
can you send me the t67 and m6a2e1 out there please?  I just have to copy his nickname and send a request right?

**Comment by MaxiiAlfaro** [comment]
the mods you have are for Android or PC?

**Comment by timurchik228** [comment]
> the mods you have are for Android or PC?

Anroid

**Comment by MaxiiAlfaro** [comment]
if i add you in vk could you send me some mods out there?  Google translator

**Comment by timurchik228** [comment]
> if i add you in vk could you send me some mods out there? Google translator

will send all the mods that I have for free, actually milking what I did this post, my nickname in VK Skril Slech

**Comment by MaxiiAlfaro** [comment]
hello there I added you in VK, I have the baidu mods in case you are interested

**Comment by ZoltisToth** [comment]
> hello there I added you in VK, I have the baidu mods in case you are interested

Hi I want some mods from baidu
