### ISSUE TITLE
Русские здесь?

### ISSUE THREAD

**Issue by Baby-SVG** [Doreamonsky/Panzer-War-Lit-Mod#67]

**Comment by timurchik228** [comment]
Здесь бро ,могу скинуть моды бесплатно ,мой вк Skril Slech

**Comment by gg-ru** [comment]
> Здесь бро ,могу скинуть моды бесплатно ,мой вк Skril Slech

У тебя есть моды которых нет здесь?

**Comment by timurchik228** [comment]
> > Здесь бро ,могу скинуть моды бесплатно ,мой вк Skril Slech
> 
> У тебя есть моды которых нет здесь?

Да,яга е100,вз 111 5а ,объект 279,260,252у защитник

**Comment by KAMEHAMEDRAGON291-1981** [comment]
> > > Скрил Слеш
> > 
> > 
> > Здесь нет моды?
> 
> Да, яга е100, вз 111 5а, объект 279,260,252у защитник
БРАТАНЧИК СКИНЬ МОДЫ НА ЭТИ ТАНКИ ПО ГУГЛ ДИСКУ ПОЖАЛУСТА

**Comment by KAMEHAMEDRAGON291-1981** [comment]
> > > Скрил Слеш
> > 
> > 
> > Здесь нет моды?
> 
> Да, яга е100, вз 111 5а, объект 279,260,252у защитник

БРАТАНЧИК СКИНЬ МОД НА ЭТИ ТАНКИ ПО ФАЙЛООБМЕНИКУ ПОЖАЛУСТА

**Comment by tigach** [comment]
timurchik228 прими заяву в вк
