### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Temirlan0947** [Doreamonsky/Panzer-War-Lit-Mod#69]
Добавьте пожалуйста pz.sfl.4c https://sketchfab.com/3d-models/pzsfl-ivc-f483dec970754cf78772f6e085041ad6

**Comment by ZoltisToth** [comment]
> Добавьте пожалуйста pz.sfl.4c https://sketchfab.com/3d-models/pzsfl-ivc-f483dec970754cf78772f6e085041ad6

This is a shit

**Comment by fk980** [comment]
Ура я зарегистрировался
