### ISSUE TITLE
AUFKLARUNGSPANZER PANTHER

### ISSUE THREAD

**Issue by A93-BEEP** [Doreamonsky/Panzer-War-Lit-Mod#70]
ADD A https://sketchfab.com/3d-models/aufklarungspanzer-panther-3770b6971d2f47f2aa169f8435b0bb95
PLEASE

**Comment by A93-BEEP** [comment]
https://sketchfab.com/3d-models/pzkpfw-vi-tiger-ausf-h-e52bf758cdb24258a2d1a480056f004c
KURO MORI MINE

**Comment by Istalinn** [comment]
No
