### ISSUE TITLE
Jg.Pz.E100 

### ISSUE THREAD

**Issue by ZoltisToth** [Doreamonsky/Panzer-War-Lit-Mod#71]
Who want him write here

**Comment by ZoltisToth** [comment]
My VK Is https://m.vk.com/id568394354

**Comment by Istalinn** [comment]
Wt?

**Comment by ZoltisToth** [comment]
> Wt?

What are u meaning

**Comment by ZoltisToth** [comment]
I HAVE ONLY ANDROID VERSION

**Comment by Istalinn** [comment]
Ok send the link

Em qui, 16 de abr de 2020 12:14, ZoltisToth <notifications@github.com>
escreveu:

**Comment by RuddyGamer** [comment]
Yo quiero el jg.pz e 100 pero no puedo iniciar sesión si alguien lo tíene envien melo en este correo andysanchezvazquez@gmail.com

**Comment by RuddyGamer** [comment]
What?
