### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#9]
Leave the advices for new mod tanks. 

Or leave the download link for 3D models here.

If you leave the link from sketchfab make sure it is a downloadable asset.

**Comment by Doreamonsky** [comment]
@AdrienPurdy  : **Could someone implement the Tetrarch and the M22 Locust into the game.

Or just make them into a mod.**


@theblackheartfox  : **https://skfb.ly/6HSDK. Someone plz make this mod for late world war**

**Comment by xazkaw** [comment]
Яга е 100,чифтан mk 6,твп т50 51,фоч155,кранвагн,удес 03,амх 13 105,лоррейн 40 тонн,объект 705а,объект 279,60 та левандовского

**Comment by xazkaw** [comment]
Яга е 100,чифтан mk 6,твп т50 51,фоч155,кранвагн,удес 03,амх 13 105,лоррейн 40 тонн,объект 705а,объект 279,60 та левандовского.ссылка https://skfb.ly/6HSDK

**Comment by xazkaw** [comment]
Можете внедрить в игру, танки:Яга е 100,чифтан mk 6,твп т50 51,фоч155,кранвагн,удес 03,амх 13 105,лоррейн 40 тонн,объект 705а,объект 279,60 та левандовского.ссылка https://skfb.ly/6HSDK

**Comment by KuzyaG** [comment]
Add Skorpion G:https://sketchfab.com/3d-models/rheinmetall-skorpion-g-f58ac175427b4dffb092e6b929c79d8d

**Comment by theblackheartfox** [comment]
Thxs developers it wpuld be a great addition to the game but plz add it to ww2late At 600 dgm pen 200 mm ap. He 185mm.hit points 1700hp 150mm of armor speed 25mph front and 15mph back. Gun depressuon front 5° sidea and back 10° traverse speed 15mph I will leave torrent speed u to who ever creates it and thank you so.much😊

**Comment by KuzyaG** [comment]
😀

**Comment by KuzyaG** [comment]
Please do this mod very please!

**Comment by theblackheartfox** [comment]
@kuzyaG I would if I could

**Comment by KuzyaG** [comment]
It's a pity

**Comment by theblackheartfox** [comment]
Like I said it woild be a great addition

**Comment by KuzyaG** [comment]
Yes

**Comment by theblackheartfox** [comment]
@kuzyaG maybe theirs someone working on it as we speak

**Comment by KuzyaG** [comment]
Probably

**Comment by KuzyaG** [comment]
How do I want to see this mod in the game ...

**Comment by KuzyaG** [comment]
I really hope that he will make it

**Comment by theblackheartfox** [comment]
@kuzyaG me too it will be a great tank of they make it with the tank description above

**Comment by KuzyaG** [comment]
Ie they already make a mod?

**Comment by sergeivasiliev** [comment]
хотель бы увидеть мод в игре Panzer War

**Comment by KuzyaG** [comment]
+

**Comment by theblackheartfox** [comment]
@sergeivasiliev да, я хотел бы видеть, что мод плз сделать это, если вы можете

**Comment by theblackheartfox** [comment]
@sergeivasiliev Было бы замечательно, если бы ypu мог добавить дополнения к игре, добавив это описание в игру, но, пожалуйста, добавьте его в ww2late при 600 dgm pen 200 mm ap. Он 185mm.hit указывает на 1700hp 150 мм скорости брони 25 миль в час спереди и 15 миль в час сзади. Депрессия пистолета спереди 5 ° в сторону и назад 10 ° скорость хода 15 миль / ч

**Comment by KuzyaG** [comment]
+++

**Comment by StrelokTvHd** [comment]
Добавьте Карл, Т-35А, VK 72.01.K, Tks. 20 mm, VK 168.01 P Плииз))

**Comment by Den71rus2005** [comment]
Я бы хотел увидеть в игре ИС-7, Об.268\4, КВ-44, Jag.Pz.E100, Т-49

**Comment by VietcongHereToBanzai** [comment]
The multiplayer prerelease what is that? I tried everything i still didnt get it it was all set it had a check mark on the mod hub but it no work, why?

**Comment by theblackheartfox** [comment]
I tell y'all what with the new updates I have seen son buffs amd nerfs to many tanks the e100 buffed smh to 820 from 720 max
And the reload time on some tanks have changed but it still makes it a great game

**Comment by AdrienPurdy** [comment]
I can't make mods for this game as I'm playing it on android and don't have windows or Mac os.

**Comment by NEXT29297** [comment]
T95 https://sketchfab.com/3d-models/t95-1acfe83e5b9f4e3aa1a6e96eb90b867a

**Comment by StrelokTvHd** [comment]
Я бы хотел видеть данные машины в игре
Т-34 Экранированный - https://sketchfab.com/3d-models/eb48044331e74b71984cc0d5bf8faba2
Su-130ПМ - https://sketchfab.com/3d-models/9bcf04f3b21045aaada26acc58d9ab44
Т-44-100 - https://sketchfab.com/3d-models/t-44-100-ea6cf07cd84647eeb5e04f3724fa0537
Su-122-54 - https://sketchfab.com/3d-models/su-122-54-de9cb367d07943159432419eeb3bca07
Tks.20 mm - https://sketchfab.com/3d-models/tks-z-nkm-20-mm-dcf7028e7fbd496889c57c8514703b7b
VK 168.01 K - https://sketchfab.com/3d-models/vk-16801-p-7113c631f7df4f048e7e57945303ccfe
ELC EVEN 90 - https://sketchfab.com/3d-models/elc-even-90-f4fe27fefb8242e5b52229804b51a439
Fv215b - https://sketchfab.com/3d-models/fv215b-58ec5695e6ea4eefafe986fd7739468a
T-103 - https://sketchfab.com/3d-models/t-103-827842ac27c84ad09c675aa1108872c4
TOG II - https://sketchfab.com/3d-models/tog-ii-ece13318dbda483ca0adeda5ae95c3f1
Lorraine 40t - https://sketchfab.com/3d-models/lorraine-40-t-c5d0df6304b24ddfa4e8ee13253a6d4b
Defender - https://sketchfab.com/3d-models/object-252u-defender-61976e2dbbb947deb3fcc1ab207952e4
Fcm 36 Pak 40 - https://sketchfab.com/3d-models/fcm-36-pak-40-ebff72961d9241588bec34907c1cd3f4
Kv-4 Kreslavskiy - https://sketchfab.com/3d-models/kv-4-kreslavskiy-5b70632ac37841ffb9c8daa1734b734d
Scorpion G - https://sketchfab.com/3d-models/rheinmetall-skorpion-g-f58ac175427b4dffb092e6b929c79d8d
T-45 - https://sketchfab.com/3d-models/t-45-5b8e4300816c4a6cadc3035a42df5311
T-28 F30 - https://sketchfab.com/3d-models/t-28-f30-44d1253897d24ec68aed45fef08516cb
BT-7A - https://sketchfab.com/3d-models/bt-7a-dfc64bc12bde459e84a2e99aa6267a2b?cursor=cD0yMDE2LTAzLTE4KzA5JTNBMjAlM0E1NS42MTU2NDYmbz02Mw%3D%3D
Пожалуйста добавьте хотя-бы несколько машин, заранее спасибо))

**Comment by theblackheartfox** [comment]
@Doreamonsky  issue i have is when the games updates i have to find a new and completely arrange the sensitivity level. but otherwise good game.

**Comment by theblackheartfox** [comment]
When y'all add the is-7 plz put it in fge ww2 late era plz

**Comment by theblackheartfox** [comment]
Can yall please fix auto aim it doesn't stay on tgt

**Comment by skina555** [comment]
by not design the panzer x

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/T-80

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/1K17_Szhatie

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/Landkreuzer_P_1500_Monster

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/T-10

**Comment by skina555** [comment]
https://en.m.wikipedia.org/wiki/Object_279

**Comment by skina555** [comment]
https://en.m.wikipedia.org/wiki/Object_785

**Comment by skina555** [comment]
https://en.m.wikipedia.org/wiki/Panzer_IX_and_Panzer_X

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/T-14_Armata

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/T-15_Armata

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/Epoch_RCWS

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/Ob%C3%BAs_autopropulsado_Koalitsiya-SV

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/Ob%C3%BAs_autopropulsado_Tipo_99_de_155_mm

**Comment by skina555** [comment]
https://en.m.wikipedia.org/wiki/Schwerer_Gustav

**Comment by skina555** [comment]
https://en.m.wikipedia.org/wiki/8.8_cm_Pak_43

**Comment by skina555** [comment]
https://en.m.wikipedia.org/wiki/24_cm_Theodor_Bruno_Kanone_(E)

**Comment by skina555** [comment]
https://en.m.wikipedia.org/wiki/ZiS-30

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/Sturer_Emil

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/VK_45.01_(P)

**Comment by skina555** [comment]
https://es.m.wikipedia.org/wiki/Elefant

**Comment by fratisekmatuska** [comment]
Can you add IS 7, FV 217 BADGER, T110E3, KV 8, OBJ 252U DEFENDER and OBJ. 268-4 thanks.

**Comment by Gamesrfry** [comment]
Hey there are rendering engine option in the settings right there are four types so what are the differences between those four rendering engine?

**Comment by theblackheartfox** [comment]
@Gamesrfry if you mean rhe one in the setting then those are the games graphics

**Comment by BlockedPanther** [comment]
http://3dmag.org/en/market/item/4520/   
I will be very thankful if you will add this

**Comment by amelkikh** [comment]
Hi there!
How about creating game virtual environment of World of Tanks for Machine Learning?
Reply me please if you're interested

**Comment by Olt13** [comment]
Т-14 Армата
T-14-152 Армата
BT-42
Т-34-76 1940 года

**Comment by nine9999nine9999** [comment]
T26E4 super pershing tank! please.

**Comment by piibr** [comment]
T64b ,m6a2e1,object 252u ,object 140 object 263

**Comment by giffany** [comment]
can someone mod the italian tankette cv-33 into panzer war?

https://sketchfab.com/3d-models/ansaldo-fiat-carro-veloce-33-l3-231d08dfd3cb4fec8699c3ede6fa0f63

**Comment by skina555** [comment]
T-14 Armata

**Comment by skina555** [comment]
Warffentrager AUF Pz IV

**Comment by skina555** [comment]
T-64
T-84

**Comment by skina555** [comment]
BM Bulat

**Comment by skina555** [comment]
Zulfiqar

**Comment by skina555** [comment]
Tipo 90 Kyū-maru

**Comment by giffany** [comment]
t95/t28

**Comment by skina555** [comment]
why don't they make a mod about using the machine guns of all the tanks in the game

**Comment by giffany** [comment]
600mm karl gerat

**Comment by skina555** [comment]
T28 Super Heavy Tank

**Comment by giffany** [comment]
kugelpanzer lol

**Comment by skina555** [comment]
Jajajajajajajajaja

**Comment by skina555** [comment]
105 mm gun T5E1

**Comment by skina555** [comment]
Marder III Ausf. M

**Comment by giffany** [comment]
railway gun "dora"

**Comment by giffany** [comment]
152mm t49

**Comment by skina555** [comment]
Kanonenjagdpanzer

**Comment by giffany** [comment]
brummbar

**Comment by giffany** [comment]
porsche tiger

**Comment by skina555** [comment]
Sd.Kfz. 164 Nashorn

**Comment by giffany** [comment]
hmmm.....*p1000 ratte*

**Comment by skina555** [comment]
you will fly us in a thousand pieces

**Comment by giffany** [comment]
yeah i forgot the size of that behemoth...

**Comment by skina555** [comment]
Jajaja jajaja jajaja

**Comment by giffany** [comment]
what about is-360? :v

**Comment by skina555** [comment]
why aren't you at NASA friend

**Comment by skina555** [comment]
imagine a game of ships from the second world war and modern

**Comment by skina555** [comment]
it is very powerful and strong but little speed the IS 7

**Comment by CahyoKusum** [comment]
https://skfb.ly/6JxHs add this tank pls im very very want it

**Comment by Object252U** [comment]
Hello,can you add T30 and KRV pls😌

**Comment by KujouOct** [comment]
I'm thinking if you can let players change the parameters like armor or the main gun max and min angle in the game, because most players dont want to use Unity to modift. That should be very funny.

**Comment by giffany** [comment]
and change the speed too? i would love to drift on a maus lmao

**Comment by piibr** [comment]
M60a3


Em qua, 14 de ago de 2019 12:10 PM, giffany <notifications@github.com>
escreveu:

> and change the speed too? i would love to drift on a maus lmao
>

**Comment by therealzinogre16** [comment]
The su 152, pz SFL.IV.c, and the grille 15

**Comment by Object252U** [comment]
Sir,cheat for training isn't work,can you fix it pls😀

**Comment by HunGabi22** [comment]
Please, make the wz 111 model 5 A
Here is the link for the 3D model:
https://sketchfab.com/3d-models/wz-111-model-5a-c39a46277a4d462ca1e84ea9ad7b96ae

**Comment by HunGabi22** [comment]
The WZ is my dream tank, it would have 1700 hit points I think.
Please make it. ✌️

**Comment by monokuma966** [comment]
Please, i need one of this in the game: https://sketchfab.com/3d-models/tank-walker-3f0d814fe3774a39a2f67b2bca0740b6

https://sketchfab.com/3d-models/a7v-walker-mk2-2788766237f4478db0cee7b65f46efed

(i have alredy tried to make them by myself, but it's so much dificult and i don't undertand a lot of things...)

**Comment by theblackheartfox** [comment]
That's hard to do not even possible only tracked vehicles

**Comment by monokuma966** [comment]
Hello again, could be added one of this vehicles?

https://sketchfab.com/3d-models/astron-superheavy-chick-hen-d1084431438844819771984d42edc1b8

https://sketchfab.com/3d-models/sobivo-medium-tank-6a96287eb7674d48ac623973ef314346

https://sketchfab.com/3d-models/u-19-1775f4b04e7043ae9d19899c71648fbf

**Comment by NSNArcade** [comment]
M1A2 Abrams https://sketchfab.com/3d-models/m1a1-abrams-tank-low-poly-3d-model-483321cd6c1147b0848a8869ad0569a6

**Comment by tankistik** [comment]
Add please ob.268 https://sketchfab.com/3d-models/object-268-b4531e965a554a6d8b9229b3a6466168

**Comment by piibr** [comment]
Add m41 Walker Bulldog


Em qua, 11 de set de 2019 1:57 PM, tankistik <notifications@github.com>
escreveu:

**Comment by piibr** [comment]
M41 Walker Bulldog have 850 hp 165 mm Pen Power on AP APCR 220 mm penetration Power he 45mm armor is 25 mm on all tank add to ww2 late

**Comment by Szymon250404** [comment]
Maybe Grille 15?
https://sketchfab.com/3d-models/grille-15-05310d10c3ce4882b8f54bd4ce7935e1

**Comment by daenarvon-dolbaeb** [comment]
add a t22 medium from 2015 with 20mm riddles e25 jagd pz e100 e50 e50m t95/chieftain and chieftain from global map please

**Comment by Cristidanu** [comment]
Here Grille 15 download link:
https://app.mediafire.com/content/myfiles

Pls make it a panzer war tank with same reload speed of WT pz4 or slower.

**Comment by Cristidanu** [comment]
My other comment has a texture and 3D model of Grille 15

**Comment by Moonlight84** [comment]
It would be very nice to see the following tanks in the game.
BT-42: https://sketchfab.com/3d-models/bt-42-keizokuver-4ecdfe3713b840f1aa19c1566f8c6d6c
Type 89: https://sketchfab.com/3d-models/type-89-i-gochi-ro-5d4ee23f6b8044a08746d21e5196d740
Pz 38H: https://sketchfab.com/3d-models/panzerkampfwagen-38h-735f-1e6b5e5707b5448aadf5f15c7183c06c
T-46:https://sketchfab.com/3d-models/t-46-625ca7b1f3cc4c809c4c38c400979b48
And: https://sketchfab.com/3d-models/s-pz-sp-wg-75-cm-sd-kfz-234-3-923d2f656060438bbae1fc3ec6947350
Arl 44..

**Comment by QPilot** [comment]
Someone so do a mod for the German project tank of the P.1000 Ratte as big as possible just for fun!

**Comment by fury1945** [comment]
How about m1a2 tusk with a tan camo because the model is plain https://sketchfab.com/3d-models/wip-abrams-m1a2-tusk-2-efb7311b641f4a76afff19e5f3068298

**Comment by fury1945** [comment]
Here is the better model https://sketchfab.com/3d-models/m1a2-abrams-4313e55af2184fe3bcd9ddc25b5f062b

**Comment by 88Mansur88-afk** [comment]
Хочу жрать!¡

**Comment by fury1945** [comment]
Here is the downloadable link for the m1a2 model

**Comment by fury1945** [comment]
https://sketchfab.com/3d-models/m1-abrams-tank-rawscan-578ef0653fb6487195cdd269cf8b5f65 the downloadable link for the m1a2 model

**Comment by fury1945** [comment]
Or maybe this one is a good model for the m1a2 https://sketchfab.com/3d-models/us-m1-abrams-2863f8e80b0149469758f7a5c71448aa

**Comment by monokuma966** [comment]
Leonardo Da Vinci's tank: https://free3d.com/3d-model/carro-armato-leonardo-da-vinci-111444.html
Cat tank: https://sketchfab.com/3d-models/tank-cat-afec0186c75f447db3ca880427765b25
Sarubia: https://sketchfab.com/3d-models/sarubia-b6ae94e664fe46c596a414a12c0f52ab

**Comment by PotkanCZ** [comment]
Hi. Can you add to mods MORSER KARL GERAT? Thank you.
https://www.3dcadbrowser.com/3d-model/morser-karl-gerat

Dne čt 14. lis 2019 22:10 uživatel fury1945 <notifications@github.com>
napsal:

**Comment by Cristidanu** [comment]
Could someone help me
When I make a modpack it is 4KB and it doesn't even work
But the other mods that I have downloaded is 4 to 6 MB please help me

**Comment by gamerboyx44** [comment]
can you add the jg pz e100, t49, arl 44, and the italian p40?

**Comment by CahyoKusum** [comment]
![Screenshot_2019-12-16-14-21-52-905_com shanghaiwindy PanzerWarOpenSource](https://user-images.githubusercontent.com/48149335/70896496-66de2480-2023-11ea-99e3-7094f56f156c.png)
How to solve that?

**Comment by Cristidanu** [comment]
> ![Screenshot_2019-12-16-14-21-52-905_com shanghaiwindy PanzerWarOpenSource](https://user-images.githubusercontent.com/48149335/70896496-66de2480-2023-11ea-99e3-7094f56f156c.png)
> How to solve that?

Maybe the material fix mod will work?

**Comment by Farhan160** [comment]
Pls. Add tank vk 90.01

**Comment by Cristidanu** [comment]
> Could someone help me
> When I make a modpack it is 4KB and it doesn't even work
> But the other mods that I have downloaded is 4 to 6 MB please help
> Nobody will help no
> Not even Doreamonsky
> Sad :(

Pls help

**Comment by PotkanCZ** [comment]
Hello Doreamonsky. Can you make in Panzer War modul system like in Cry of
War? Thank you 🙏🙂

Dne pá 20. pro 2019 12:04 uživatel Cristidanu <notifications@github.com>
napsal:

**Comment by FAJAgaming** [comment]
You can add K Wagen

**Comment by yarusskiy123** [comment]
Please,add slow ATGM

**Comment by timurchik228** [comment]
> Можете внедрить в игру, танки:Яга е 100,чифтан mk 6,твп т50 51,фоч155,кранвагн,удес 03,амх 13 105,лоррейн 40 тонн,объект 705а,объект 279,60 та левандовского.ссылка https://skfb.ly/6HSDK



> @AdrienPurdy : Could someone implement the Tetrarch and the M22 Locust into the game.
> 
> Or just make them into a mod.
> 
> @theblackheartfox : **https://skfb.ly/6HSDK. Someone plz make this mod for late world war**



> Leave the advices for new mod tanks.
> 
> Or leave the download link for 3D models here.
> 
> If you leave the link from sketchfab make sure it is a downloadable asset.
could you tell me why when I want to download one of the mods I get a 404 error ? tell me what to do

**Comment by timurchik228** [comment]
could you tell me why when I want to download one of the mods I get a 404 error ? tell me what to do

**Comment by HexAck0** [comment]
Hello, maybe this is the wrong place to ask this question, but: I can't seem to play the game on my phone. The app will just show a black screen, and poof, it quits. Any advice?
(Also, my phone is a Redmi 4A, it's an Android 7 version, so maybe an update ended support for android 7? Anyway, thanks.)

**Comment by Mk48-a1** [comment]
> Я бы хотел видеть данные машины в игре
> Т-34 Экранированный - https://sketchfab.com/3d-models/eb48044331e74b71984cc0d5bf8faba2
> Su-130ПМ - https://sketchfab.com/3d-models/9bcf04f3b21045aaada26acc58d9ab44
> Т-44-100 - https://sketchfab.com/3d-models/t-44-100-ea6cf07cd84647eeb5e04f3724fa0537
> Su-122-54 - https://sketchfab.com/3d-models/su-122-54-de9cb367d07943159432419eeb3bca07
> Tks.20 mm - https://sketchfab.com/3d-models/tks-z-nkm-20-mm-dcf7028e7fbd496889c57c8514703b7b
> VK 168.01 K - https://sketchfab.com/3d-models/vk-16801-p-7113c631f7df4f048e7e57945303ccfe
> ELC EVEN 90 - https://sketchfab.com/3d-models/elc-even-90-f4fe27fefb8242e5b52229804b51a439
> Fv215b - https://sketchfab.com/3d-models/fv215b-58ec5695e6ea4eefafe986fd7739468a
> T-103 - https://sketchfab.com/3d-models/t-103-827842ac27c84ad09c675aa1108872c4
> TOG II - https://sketchfab.com/3d-models/tog-ii-ece13318dbda483ca0adeda5ae95c3f1
> Lorraine 40t - https://sketchfab.com/3d-models/lorraine-40-t-c5d0df6304b24ddfa4e8ee13253a6d4b
> Defender - https://sketchfab.com/3d-models/object-252u-defender-61976e2dbbb947deb3fcc1ab207952e4
> Fcm 36 Pak 40 - https://sketchfab.com/3d-models/fcm-36-pak-40-ebff72961d9241588bec34907c1cd3f4
> Kv-4 Kreslavskiy - https://sketchfab.com/3d-models/kv-4-kreslavskiy-5b70632ac37841ffb9c8daa1734b734d
> Scorpion G - https://sketchfab.com/3d-models/rheinmetall-skorpion-g-f58ac175427b4dffb092e6b929c79d8d
> T-45 - https://sketchfab.com/3d-models/t-45-5b8e4300816c4a6cadc3035a42df5311
> T-28 F30 - https://sketchfab.com/3d-models/t-28-f30-44d1253897d24ec68aed45fef08516cb
> BT-7A - https://sketchfab.com/3d-models/bt-7a-dfc64bc12bde459e84a2e99aa6267a2b?cursor=cD0yMDE2LTAzLTE4KzA5JTNBMjAlM0E1NS42MTU2NDYmbz02Mw%3D%3D
> Пожалуйста добавьте хотя-бы несколько машин, заранее спасибо))

We need this tanks

**Comment by scp174** [comment]
Can someone make a mod that adds the  Crusader (aka mark IV)

**Comment by MaxiiAlfaro** [comment]
Agreguen el tog ii y m103 porfa

**Comment by timurchik228** [comment]
Pls add caernarvon in github ,beaucase I can't download in Bai du  .

**Comment by MaxiiAlfaro** [comment]
> Pls add caernarvon in github ,beaucase I can't download in Bai du .

how to upload to github?  I do not know how to do it.  Google translator

**Comment by MaxiiAlfaro** [comment]
> Por favor agregue caernarvon en github, porque no puedo descargar en Bai du.

I have the mods that I download from baidu, if you want I can pass them on to you

**Comment by ivanIRIJ** [comment]
It would be better if you put this tanks in the game:
Chimera- https://sketchfab.com/3d-models/chimera-efde42f67c85445c9047fde80f2c8448
Lansen C- https://sketchfab.com/3d-models/lansen-c-b2e2a6304c534d5da1019894d6ab5b6e
Primo Victoria- https://sketchfab.com/3d-models/primo-victoria-08d4a51327ac4afdbd19e4d805dbf853
T34- https://sketchfab.com/3d-models/t34-f6c78b17cfd5438292754a068f4931f3
M4A3E8 Fury- https://sketchfab.com/3d-models/m4a3e8-fury-4762ca87a84243ce887ef0f61fede2db
Panther/M10- https://sketchfab.com/3d-models/pantherm10-2e1f18e8cce8432ab7759185cdb35e43
T26E4 SuperPershing- https://sketchfab.com/3d-models/t26e4-superpershing-520a985962a84876819fdbef51b201a9
17pdr sp Achilles- https://sketchfab.com/3d-models/achilles-ff49b5ce12b1498ab34d5496c5db96db
M18 hellcat- https://sketchfab.com/3d-models/m18-hellcat-60c88e10478a46f39bd98953512e54b2
M36 jackson- https://sketchfab.com/3d-models/m36-jackson-5126a8fc8d374412a3bbe2ad0d8b3299

**Comment by NEXT29297** [comment]
How to control heli in Android, idk how to play T-T
